src/files/templates/demomarket/js/apiship/initialize_widget.js, src/files/templates/demomarket/php/emarket/delivery/choose/apiship.phtml
http://youtrack.umisoft.ru/issue/cms2-2934
=> cms2-2934 изменил пути к файлам

src/files/templates/demomarket/xslt/modules/news.xsl
http://youtrack.umisoft.ru/issue/cms2-2956
=> cms2-2956 Поправил вызов autothumbs

src/files/templates/demomarket/php/library/DemomarketPhpExtension.php
http://youtrack.umisoft.ru/issue/bc-2052
=> bc-2052 Добавлен учет скидки при выводе цен торгового предложения

src/files/templates/demomarket/php/layout/head.phtml, src/files/templates/demomarket/php/library/DemomarketPhpExtension.php
http://youtrack.umisoft.ru/issue/cms2-3059
=> cms2-3059 Подключено новое расширение

dump/dump.sql, src/files/templates/demomarket/php/emarket/delivery/choose/apiship.phtml, src/files/templates/demomarket/php/library/DemomarketPhpExtension.php
http://youtrack.umisoft.ru/issue/bc-2093
=> bc-2093 Добавил настройки API Key для Яндекс карт в виджете доставки ApiShip

src/files/templates/demomarket/css/appointment.css, src/files/templates/demomarket/js/appointment/lib.js, src/files/templates/demomarket/php/appointment/page.phtml, src/files/templates/demomarket/php/library/DemomarketPhpExtension.php, src/files/templates/demomarket/php/library/captcha/classic.phtml
http://youtrack.umisoft.ru/issue/cms2-3097
=> cms2-3097 Добавил каптчу в форму Онлайн-запись

dump/dump.sql
http://youtrack.umisoft.ru/issue/cms2-3015
=> cms2-3015 Добавил пользователю поле с токеном авторизации

src/files/templates/demomarket/php/emarket/payment/payonline.phtml
http://youtrack.umisoft.ru/issue/cms2-3105
=> cms2-3105 Исправлена форма оплаты через PayOnline

src/files/templates/demomarket/config.ini
http://youtrack.umisoft.ru/issue/bc-2167
=> bc-2167 Поправил путь для подключения класса SeoPhpExtension

src/files/templates/demomarket/package-lock.json, src/files/templates/demomarket/package.json
http://youtrack.umisoft.ru/issue/cms2-3192
=> cms2-3192 Обновлены уязвимые npm пакеты

src/files/templates/demomarket/less/media.less, src/files/templates/demomarket/less/style.less, src/files/templates/demomarket/less/tooltip.less
http://youtrack.umisoft.ru/issue/cms2-3315
=> Правки верстки выпадющего списка корзины.

src/files/templates/demomarket/php/emarket/payment/robox.phtml
http://youtrack.umisoft.ru/issue/cms2-3355
=> cms2-3355 Добавлена передача информации о валюте для Robokassa

src/files/templates/demomarket/php/emarket/payment/invoice.phtml
http://youtrack.umisoft.ru/issue/cms2-3374
=> cms2-3374 Добавлен вывод информации о сохраненных юридических лицах

src/files/templates/demomarket/gulpfile.js
http://youtrack.umisoft.ru/issue/cms2-3409
=> cms2-3409 Добавил информацию о модуле push-уведомления в gulpfile

src/files/templates/demomarket/php/library/DemomarketPhpExtension.php
http://youtrack.umisoft.ru/issue/cms2-3439#comment=98-54375
=> Исправлен поиск по сайту

src/files/templates/demomarket/less/main_window.less
http://youtrack.umisoft.ru/issue/umicmsru-733
=> Поправить верстку цен в корзине при оформлении заказа в 1 шаг

src/files/templates/demomarket/php/catalog/category/preview.phtml, src/files/templates/demomarket/php/catalog/product/preview/image.phtml, src/files/templates/demomarket/php/content/home/mobile_timer.phtml, src/files/templates/demomarket/php/emarket/cart/product/image.phtml, src/files/templates/demomarket/php/layout/header/middle/cart/popup.phtml, src/files/templates/demomarket/php/library/DemomarketPhpExtension.php, src/files/templates/demomarket/php/library/thumbnail.phtml, src/files/templates/demomarket/php/news/item/photo.phtml, src/files/templates/demomarket/php/photoalbum/album.phtml, src/files/templates/demomarket/php/photoalbum/photo.phtml
http://youtrack.umisoft.ru/issue/cms2-3443
http://youtrack.umisoft.ru/issue/cms2-3365#comment=98-54431
http://youtrack.umisoft.ru/issue/cms2-3365#comment=98-54547
=> cms2-3443 Добаввил элементам изображений атрибуты для передачи в файловый менеджер

src/files/templates/demomarket/less/main_window.less
http://youtrack.umisoft.ru/issue/cms2-3494
=> Уменьшил длину названия товаров в заказе

src/files/templates/demomarket/php/errors.phtml, src/files/templates/demomarket/php/library/error.phtml, src/files/templates/demomarket/php/webforms/send.phtml
http://youtrack.umisoft.ru/issue/bc-2304
=> bc-2304 Добавил вывод ошибок в случае отключенного редиректа при отправке сообщений

src/files/templates/demomarket/php/layout/modal/login.phtml
http://youtrack.umisoft.ru/issue/cms2-3480
http://youtrack.umisoft.ru/issue/cms2-3481
=> Удалены instagram и twitter из виджета регистрации ulogin

src/files/templates/demomarket/less/main_window.less, src/files/templates/demomarket/less/media.less
http://youtrack.umisoft.ru/issue/cms2-3475
=> Правка окна поиска на мобильных экранах

src/files/templates/demomarket/php/library/DemomarketPhpExtension.php
http://youtrack.umisoft.ru/issue/cms2-3570
=> cms2-3570 Исправлено отображение множественных полей в характеристиках торговых предложений

src/files/templates/demomarket/php/library/DemomarketPhpExtension.php
http://youtrack.umisoft.ru/issue/cms2-3570
=> cms2-3570 Исправлно отображение мульти полей когда они пустые

src/files/templates/demomarket/php/appointment/page.phtml
https://youtrack.umisoft.ru/issue/bc-2387
Исправлена работа кнопки "Мне все равно" при онлайн записи
=> bc-2387 Исправлена работа кнопки "Мне все равно" при онлайн записи

src/files/templates/demomarket/php/library/DemomarketPhpExtension.php
https://youtrack.umisoft.ru/issue/bc-2399
=> bc-2399 Скрыты характеристики, которые в типе данных не помечены как "Видимые"

src/files/templates/demomarket/js/apiship/initialize_widget.js
https://youtrack.umisoft.ru/issue/bc-2415
=> bc-2415 Исправлена работа виджета apiship

src/files/templates/demomarket/php/photoalbum/photo.phtml
https://youtrack.umisoft.ru/issue/cms2-3794
=> cms2-3794 Исправил ошибку на страницах фотографий
